// Barrel re-export — all existing `import { ... } from "@/types"` continue to work.
// For new code, prefer importing directly from the domain file:
//   import type { Client } from "@/types/client"

export * from "./user"
export * from "./client"
export * from "./contract"
export * from "./financial"
export * from "./meeting"
export * from "./report"
export * from "./pipeline"
export * from "./automation"
export * from "./activity"
export * from "./integration"
export * from "./settings"
export * from "./dashboard"
export * from "./campaign"
export * from "./organization"
export * from "./onboarding"
export * from "./task"
export * from "./portal"
